// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Railway_Reservation_Sys;

#nullable disable

namespace Railway_Reservation_Sys.Migrations
{
    [DbContext(typeof(RailwayReservationDbContext))]
    partial class RailwayReservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Coach", b =>
                {
                    b.Property<int>("CoachID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachID"));

                    b.Property<string>("CoachNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleID")
                        .HasColumnType("int");

                    b.HasKey("CoachID");

                    b.HasIndex("ScheduleID");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PassengerID");

                    b.HasIndex("UserID");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmtStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentID");

                    b.HasIndex("ReservationID");

                    b.HasIndex("UserID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.ReservationDetails", b =>
                {
                    b.Property<int>("ReservationDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationDetailID"));

                    b.Property<int?>("CoachID")
                        .HasColumnType("int");

                    b.Property<decimal>("FarePerSeat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PassengerID")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<int?>("SeatID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationDetailID");

                    b.HasIndex("CoachID");

                    b.HasIndex("PassengerID");

                    b.HasIndex("ReservationID");

                    b.HasIndex("SeatID");

                    b.ToTable("ReservationDetails");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.ReservationHeader", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<int?>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRefund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationID");

                    b.HasIndex("ScheduleID");

                    b.HasIndex("TrainID");

                    b.HasIndex("UserID");

                    b.ToTable("ReservationHeaders");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID");

                    b.HasIndex("TrainID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Seat", b =>
                {
                    b.Property<int>("SeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatID"));

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<int>("SeatNo")
                        .HasColumnType("int");

                    b.Property<string>("SeatStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatID");

                    b.HasIndex("CoachID");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Station", b =>
                {
                    b.Property<int>("StationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationID"));

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationID");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Train", b =>
                {
                    b.Property<int>("TrainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainID"));

                    b.Property<DateTime>("DestiArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationID")
                        .HasColumnType("int");

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SourceDepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceID")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainID");

                    b.HasIndex("DestinationID");

                    b.HasIndex("SourceID");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Coach", b =>
                {
                    b.HasOne("Railway_Reservation_Sys.Models.Schedule", "Schedule")
                        .WithMany("Coaches")
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Passenger", b =>
                {
                    b.HasOne("Railway_Reservation_Sys.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Payment", b =>
                {
                    b.HasOne("Railway_Reservation_Sys.Models.ReservationHeader", "ReservationHeader")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railway_Reservation_Sys.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationHeader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.ReservationDetails", b =>
                {
                    b.HasOne("Railway_Reservation_Sys.Models.Coach", "Coach")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Railway_Reservation_Sys.Models.Passenger", "Passenger")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("PassengerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Railway_Reservation_Sys.Models.ReservationHeader", "ReservationHeader")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Railway_Reservation_Sys.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coach");

                    b.Navigation("Passenger");

                    b.Navigation("ReservationHeader");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.ReservationHeader", b =>
                {
                    b.HasOne("Railway_Reservation_Sys.Models.Schedule", "Schedule")
                        .WithMany("ReservationHeaders")
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Railway_Reservation_Sys.Models.Train", "Train")
                        .WithMany("ReservationHeaders")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Railway_Reservation_Sys.Models.User", "User")
                        .WithMany("ReservationHeaders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Train");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Schedule", b =>
                {
                    b.HasOne("Railway_Reservation_Sys.Models.Train", "Train")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Seat", b =>
                {
                    b.HasOne("Railway_Reservation_Sys.Models.Coach", "Coach")
                        .WithMany("Seats")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Train", b =>
                {
                    b.HasOne("Railway_Reservation_Sys.Models.Station", "DestinationStation")
                        .WithMany()
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Railway_Reservation_Sys.Models.Station", "SourceStation")
                        .WithMany()
                        .HasForeignKey("SourceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationStation");

                    b.Navigation("SourceStation");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Coach", b =>
                {
                    b.Navigation("ReservationDetails");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Passenger", b =>
                {
                    b.Navigation("ReservationDetails");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.ReservationHeader", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ReservationDetails");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Schedule", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("ReservationHeaders");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.Train", b =>
                {
                    b.Navigation("ReservationHeaders");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Railway_Reservation_Sys.Models.User", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ReservationHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
